# Site settings
title: Photography by Roach Haus
description: Photography portfolio for Katie Ball of <a href="http://roachhd">Roach Haus Designs</a>
baseurl: "/lens/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Katie Ball

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/roachhd
googleplus_url: https://plus.google.com/u/0/+roachhd
instagram_url:
linkedin_url: https://www.linkedin.com/in/roachhd
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mektball

# Build settings
markdown: kramdown
